name: Docker Compose CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docker-test:
    name: Test Docker Compose
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker images
      run: docker-compose build
    
    - name: Start services
      run: docker-compose up -d
    
    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to start..."
        sleep 30
        docker-compose ps
    
    - name: Check Auth Service health
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:3000 || [ $? -eq 52 ]; do sleep 2; done'
        echo "Auth service is running"
    
    - name: Check Product Service health
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:3001 || [ $? -eq 52 ]; do sleep 2; done'
        echo "Product service is running"
    
    - name: Check API Gateway health
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:3003 || [ $? -eq 52 ]; do sleep 2; done'
        echo "API Gateway is running"
    
    - name: Show service logs
      if: failure()
      run: docker-compose logs
    
    - name: Cleanup
      if: always()
      run: docker-compose down -v
